np.sort <br>
Return a sorted copy of an array <br>
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a=np.random.randint(1,100,15)
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [2]:
np.sort(a)

array([10, 19, 22, 27, 42, 45, 49, 49, 62, 64, 70, 71, 73, 76, 79])

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)

In [4]:
b

array([[40, 68, 53, 45],
       [73, 53, 27, 97],
       [71, 79, 85, 90],
       [ 8, 47,  1, 34],
       [82, 85, 53, 15],
       [88, 61, 57, 62]])

In [5]:
np.sort(a)

array([10, 19, 22, 27, 42, 45, 49, 49, 62, 64, 70, 71, 73, 76, 79])

In [6]:
np.sort(b)

array([[40, 45, 53, 68],
       [27, 53, 73, 97],
       [71, 79, 85, 90],
       [ 1,  8, 34, 47],
       [15, 53, 82, 85],
       [57, 61, 62, 88]])

In [8]:
np.sort(b,axis=0)

array([[ 8, 47,  1, 15],
       [40, 53, 27, 34],
       [71, 61, 53, 45],
       [73, 68, 53, 62],
       [82, 79, 57, 90],
       [88, 85, 85, 97]])

np.append <br>
The numpy.append() appends values along the mentioned axis at the end of the array <br>

https://numpy.org/doc/stable/reference/generated/numpy.append.html <br>

In [10]:
# code
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [11]:
np.append(a,200)

array([ 19,  45,  27,  62,  10,  42,  49,  76,  73,  79,  64,  49,  71,
        70,  22, 200])

In [12]:
b

array([[40, 68, 53, 45],
       [73, 53, 27, 97],
       [71, 79, 85, 90],
       [ 8, 47,  1, 34],
       [82, 85, 53, 15],
       [88, 61, 57, 62]])

In [14]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[40., 68., 53., 45.,  1.],
       [73., 53., 27., 97.,  1.],
       [71., 79., 85., 90.,  1.],
       [ 8., 47.,  1., 34.,  1.],
       [82., 85., 53., 15.,  1.],
       [88., 61., 57., 62.,  1.]])

In [15]:
# np.concatenate
# numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
# code
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [20]:
# np.unique
# With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

# https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [21]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [22]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [23]:
# np.expand_dims
# With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

# https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
# code
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [27]:
np.expand_dims(a,axis=0)

array([[19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22]])

In [28]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [29]:
np.expand_dims(a,axis=1)

array([[19],
       [45],
       [27],
       [62],
       [10],
       [42],
       [49],
       [76],
       [73],
       [79],
       [64],
       [49],
       [71],
       [70],
       [22]])

In [30]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [31]:
# np.where
# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

# https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [32]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [33]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  7,  8,  9, 10, 12, 13], dtype=int64),)

In [34]:
# replace all values >50 with 0

In [35]:
np.where(a>50,0,a)

array([19, 45, 27,  0, 10, 42, 49,  0,  0,  0,  0, 49,  0,  0, 22])

In [36]:
np.where(a%2==0,0,a)

array([19, 45, 27,  0,  0,  0, 49,  0, 73, 79,  0, 49, 71,  0,  0])

In [37]:
# np.argmax
# The numpy.argmax() function returns indices of the max element of the array in a particular axis.

# https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [40]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [41]:
np.argmax(a)

9

In [42]:
a[np.argmax(a)]

79

In [43]:
b

array([[40, 68, 53, 45],
       [73, 53, 27, 97],
       [71, 79, 85, 90],
       [ 8, 47,  1, 34],
       [82, 85, 53, 15],
       [88, 61, 57, 62]])

In [47]:
np.argmax(b,axis=0)

array([5, 4, 2, 1], dtype=int64)

In [48]:
np.argmax(b,axis=1)

array([1, 3, 3, 1, 1, 0], dtype=int64)

In [49]:
#np.argmin
np.argmin(a)

4

In [50]:
# np.cumsum
# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

# https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [51]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [52]:
np.cumsum(a)

array([ 19,  64,  91, 153, 163, 205, 254, 330, 403, 482, 546, 595, 666,
       736, 758], dtype=int32)

In [54]:
np.cumsum(b,axis=1)

array([[ 40, 108, 161, 206],
       [ 73, 126, 153, 250],
       [ 71, 150, 235, 325],
       [  8,  55,  56,  90],
       [ 82, 167, 220, 235],
       [ 88, 149, 206, 268]], dtype=int32)

In [55]:
# np.cumprod
np.cumprod(a)

array([        19,        855,      23085,    1431270,   14312700,
        601133400, -609234472,  942820384,  106411296, -183442208,
       1144600576,  250853376,  630720512, 1200762880,  646979584],
      dtype=int32)

In [56]:
# np.percentile
# numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

# https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [57]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [58]:
np.percentile(a,50)

49.0

In [59]:
np.percentile(a,0)

10.0

In [60]:
np.percentile(a,75)

70.5

In [61]:
np.median(a)

49.0

In [62]:
# np.histogram
# Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

# https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [64]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 2, 0, 4, 0, 2, 5, 0, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [65]:
np.histogram(a,bins=[0,50,100])

(array([8, 7], dtype=int64), array([  0,  50, 100]))

In [66]:
# np.corrcoef
# Return Pearson product-moment correlation coefficients.

# https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [67]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [68]:
# np.isin
# With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

# https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [69]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [71]:
np.isin(a,[49,22,64])

array([False, False, False, False, False, False,  True, False, False,
       False,  True,  True, False, False,  True])

In [72]:
items=[10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False])

In [73]:
# np.flip
# The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

# https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [74]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [75]:
np.flip(a)

array([22, 70, 71, 49, 64, 79, 73, 76, 49, 42, 10, 62, 27, 45, 19])

In [76]:
b

array([[40, 68, 53, 45],
       [73, 53, 27, 97],
       [71, 79, 85, 90],
       [ 8, 47,  1, 34],
       [82, 85, 53, 15],
       [88, 61, 57, 62]])

In [78]:
np.flip(b,axis=0)

array([[88, 61, 57, 62],
       [82, 85, 53, 15],
       [ 8, 47,  1, 34],
       [71, 79, 85, 90],
       [73, 53, 27, 97],
       [40, 68, 53, 45]])

In [79]:
np.flip(b,axis=1)

array([[45, 53, 68, 40],
       [97, 27, 53, 73],
       [90, 85, 79, 71],
       [34,  1, 47,  8],
       [15, 53, 85, 82],
       [62, 57, 61, 88]])

In [80]:
# np.put
# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

# https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [81]:
a

array([19, 45, 27, 62, 10, 42, 49, 76, 73, 79, 64, 49, 71, 70, 22])

In [82]:
np.put(a,[0,1],[110,530])

In [83]:
a

array([110, 530,  27,  62,  10,  42,  49,  76,  73,  79,  64,  49,  71,
        70,  22])

In [84]:
# np.delete
# The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

# https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [85]:
a

array([110, 530,  27,  62,  10,  42,  49,  76,  73,  79,  64,  49,  71,
        70,  22])

In [87]:
np.delete(a,0)

array([530,  27,  62,  10,  42,  49,  76,  73,  79,  64,  49,  71,  70,
        22])

In [88]:
a

array([110, 530,  27,  62,  10,  42,  49,  76,  73,  79,  64,  49,  71,
        70,  22])

In [89]:
# Set functions
# np.union1d
# np.intersect1d
# np.setdiff1d
# np.setxor1d
# np.in1d

In [90]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
np.intersect1d(m,n)

array([3, 4, 5])

In [92]:
np.setdiff1d(m,n)

array([1, 2])

In [93]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [94]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [95]:
# np.clip
# numpy.clip() function is used to Clip (limit) the values in an array.

# https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [96]:
# code
np.clip(a,a_min=25,a_max=75)

array([75, 75, 27, 62, 25, 42, 49, 75, 73, 75, 64, 49, 71, 70, 25])