In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
#2D and 3D
b=np.array([[1,2],[3,4]])

In [6]:
b

array([[1, 2],
       [3, 4]])

In [7]:
c=np.array([[[1,2]],[[3,4]],[[5,6]]])

In [8]:
c

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [9]:
c.shape

(3, 1, 2)

In [10]:
c.ndim

3

In [11]:
b.ndim

2

In [12]:
# dtype

In [14]:
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [15]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
#with reshape
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
np.arange(16).reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [20]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
#np.ones and np.zeros

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#np.random

In [28]:
np.random.random((3,4))

array([[0.93094068, 0.32936567, 0.15547207, 0.20825426],
       [0.21683391, 0.3744645 , 0.79775555, 0.27531916],
       [0.01687585, 0.15072062, 0.21573083, 0.69551734]])

In [29]:
np.random.random((4,4))

array([[0.92271023, 0.18875482, 0.46670122, 0.48191965],
       [0.34016935, 0.94310437, 0.62404961, 0.04605957],
       [0.52063457, 0.00505698, 0.81462598, 0.10666571],
       [0.27409198, 0.34604317, 0.6099085 , 0.5319627 ]])

In [33]:
np.random.randint((2,20))

array([0, 5])

In [35]:
np.random.randint(1,10,size=(2,2))

array([[6, 2],
       [8, 2]])

In [37]:
np.random.randint(1,20,size=(4,4))

array([[17, 11, 15, 17],
       [ 1,  4,  5, 17],
       [ 6, 10, 18, 17],
       [15, 19,  3, 12]])

In [39]:
np.random.random((3,4))

array([[0.78535947, 0.218496  , 0.9687521 , 0.66292685],
       [0.62188471, 0.12813096, 0.78933541, 0.09298336],
       [0.61268267, 0.21728552, 0.22553771, 0.05183921]])

In [42]:
#np.linspace
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.linspace(2,10,20,dtype=float)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [45]:
np.linspace(-10,20,dtype=int)

array([-10, -10,  -9,  -9,  -8,  -7,  -7,  -6,  -6,  -5,  -4,  -4,  -3,
        -3,  -2,  -1,  -1,   0,   1,   1,   2,   2,   3,   4,   4,   5,
         5,   6,   7,   7,   8,   8,   9,  10,  10,  11,  12,  12,  13,
        13,  14,  15,  15,  16,  16,  17,  18,  18,  19,  20])

In [46]:
np.linspace(1.5,2.5,50,dtype=float)

array([1.5       , 1.52040816, 1.54081633, 1.56122449, 1.58163265,
       1.60204082, 1.62244898, 1.64285714, 1.66326531, 1.68367347,
       1.70408163, 1.7244898 , 1.74489796, 1.76530612, 1.78571429,
       1.80612245, 1.82653061, 1.84693878, 1.86734694, 1.8877551 ,
       1.90816327, 1.92857143, 1.94897959, 1.96938776, 1.98979592,
       2.01020408, 2.03061224, 2.05102041, 2.07142857, 2.09183673,
       2.1122449 , 2.13265306, 2.15306122, 2.17346939, 2.19387755,
       2.21428571, 2.23469388, 2.25510204, 2.2755102 , 2.29591837,
       2.31632653, 2.33673469, 2.35714286, 2.37755102, 2.39795918,
       2.41836735, 2.43877551, 2.45918367, 2.47959184, 2.5       ])

In [47]:
np.linspace(-0.5,1,100)

array([-0.5       , -0.48484848, -0.46969697, -0.45454545, -0.43939394,
       -0.42424242, -0.40909091, -0.39393939, -0.37878788, -0.36363636,
       -0.34848485, -0.33333333, -0.31818182, -0.3030303 , -0.28787879,
       -0.27272727, -0.25757576, -0.24242424, -0.22727273, -0.21212121,
       -0.1969697 , -0.18181818, -0.16666667, -0.15151515, -0.13636364,
       -0.12121212, -0.10606061, -0.09090909, -0.07575758, -0.06060606,
       -0.04545455, -0.03030303, -0.01515152,  0.        ,  0.01515152,
        0.03030303,  0.04545455,  0.06060606,  0.07575758,  0.09090909,
        0.10606061,  0.12121212,  0.13636364,  0.15151515,  0.16666667,
        0.18181818,  0.1969697 ,  0.21212121,  0.22727273,  0.24242424,
        0.25757576,  0.27272727,  0.28787879,  0.3030303 ,  0.31818182,
        0.33333333,  0.34848485,  0.36363636,  0.37878788,  0.39393939,
        0.40909091,  0.42424242,  0.43939394,  0.45454545,  0.46969697,
        0.48484848,  0.5       ,  0.51515152,  0.53030303,  0.54

In [48]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [51]:
# Array Attributes
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [52]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [53]:
#ndim
a3.ndim

3

In [54]:
#shape
print(a3.shape)

(2, 2, 2)


In [55]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
#size
print(a3.size)

8


In [57]:
#itemsize
a3.itemsize

4

In [58]:
a1.itemsize

4

In [59]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
print(a1.itemsize)

4


In [61]:
a1.dtype

dtype('int32')

In [62]:
a2.dtype

dtype('float64')

In [63]:
a2.itemsize

8

In [64]:
#astype
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1.dtype

dtype('int32')

In [66]:
a1.astype(np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [67]:
a1.astype(np.str_)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U11')

In [68]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a1.dtype

dtype('int32')

In [73]:
a4=a1.astype(np.float16)

In [74]:
a4

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

In [75]:
a4.itemsize

2

In [78]:
# Array Operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [79]:
a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [80]:
#scalar operations
# arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [81]:
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [82]:
a2[a2==15]

array([15])

In [84]:
a2%5==0

array([[False, False, False,  True],
       [False, False, False, False],
       [ True, False, False, False]])

In [85]:
a2[a2%5==0]

array([15, 20])

In [86]:
#vector opeartions
#arithmetic
a1**a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]], dtype=int32)

In [87]:
# #Array Functions

In [93]:
a1=np.random.random((3,3))
a1

array([[0.68470772, 0.68361875, 0.40116621],
       [0.95622022, 0.88504598, 0.29589344],
       [0.57284533, 0.51873481, 0.86317214]])

In [94]:
a1=np.round(a1*100)

In [95]:
a1

array([[68., 68., 40.],
       [96., 89., 30.],
       [57., 52., 86.]])

In [96]:
# max/min/sum/prod
# 0 -> col and 1 ->row

In [97]:
a1

array([[68., 68., 40.],
       [96., 89., 30.],
       [57., 52., 86.]])

In [98]:
np.prod(a1,axis=0)

array([372096., 314704., 103200.])

In [99]:
np.prod(a1,axis=1)

array([184960., 256320., 254904.])

In [100]:
np.sum(a1,axis=0)

array([221., 209., 156.])

In [101]:
np.sum(a1,axis=1)

array([176., 215., 195.])

In [103]:
np.var(a1,axis=0) # mean/median/std/var

array([269.55555556, 229.55555556, 594.66666667])

In [104]:
#trigonometric functions

In [105]:
np.sin(a1)

array([[-0.89792768, -0.89792768,  0.74511316],
       [ 0.98358775,  0.86006941, -0.98803162],
       [ 0.43616476,  0.98662759, -0.92345845]])

In [108]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [109]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [111]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [112]:
a = [[1, 0], [0, 1]]

In [113]:
b = [[4, 1], [2, 2]]

In [114]:
a

[[1, 0], [0, 1]]

In [115]:
b

[[4, 1], [2, 2]]

In [116]:
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [117]:
# log and exponents
np.exp(a1)

array([[3.40427605e+29, 3.40427605e+29, 2.35385267e+17],
       [4.92345829e+41, 4.48961282e+38, 1.06864746e+13],
       [5.68572000e+24, 3.83100800e+22, 2.23524660e+37]])

In [118]:
# round / floor / ceil

In [123]:
np.ceil(np.random.random((2,3))*100)

array([[87., 29., 82.],
       [ 9., 69., 37.]])

In [124]:
#Indexing and Slicing

In [125]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [126]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [127]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a2[1,0]

4

In [129]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [130]:
a3[1,0,1]

5

In [131]:
a3[1]

array([[4, 5],
       [6, 7]])

In [132]:
a3[1,1]

array([6, 7])

In [133]:
a3[1,1,0]

6

In [134]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a1[2:5]

array([2, 3, 4])

In [136]:
a1[2:5:2]

array([2, 4])

In [137]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [150]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [151]:
a2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a2[1:3,2::]

array([[ 6,  7],
       [10, 11]])

In [153]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [161]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [165]:
a2[1:2,1:3]

array([[5, 6]])

In [172]:
a2[1,::3]

array([4, 7])

In [178]:
a2[0,:]

array([0, 1, 2, 3])

In [180]:
a2[:,2]

array([ 2,  6, 10])

In [181]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [182]:
a3=np.arange(27).reshape(3,3,3)

In [183]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [184]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [186]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [187]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [196]:
a3[:3,2,1::]

array([[ 7,  8],
       [16, 17],
       [25, 26]])

In [197]:
#Iterating
a

[[1, 0], [0, 1]]

In [198]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [199]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [200]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [201]:
# nditer
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [202]:
# Transpose
a1.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [204]:
a3.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [212]:
#ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [213]:
# Stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [214]:
a4,a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [215]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [216]:
# verical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [217]:
# Spliting

In [218]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [222]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [224]:
np.vsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]