### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [19]:
import numpy as np
#np.array

In [20]:
a=np.array([1,2,3,4])

In [21]:
a

array([1, 2, 3, 4])

In [22]:
#2D and 3D
b=np.array([[1,2],[3,4]])

In [23]:
b

array([[1, 2],
       [3, 4]])

In [30]:
b.ndim # ndim tells the array dimension
b.shape

(2, 2)

In [26]:
three_3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [27]:
three_3d.ndim

3

In [28]:
three_3d.shape # shape 

(2, 2, 2)

In [29]:
three_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
#dtype
np.array([10,20,30],dtype=int)

array([10, 20, 30])

In [53]:
#np.arange
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
np.arange(1,13,2)

array([ 1,  3,  5,  7,  9, 11])

In [66]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
np.arange(1,13).reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [67]:
#np.ones and np.zeros

In [69]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
# np.random
np.random.random((3,4))

array([[0.99768054, 0.09848933, 0.05466486, 0.04939705],
       [0.23406177, 0.1794738 , 0.54348365, 0.75952002],
       [0.62369605, 0.38976478, 0.77834287, 0.00196145]])

In [74]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [75]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [77]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [78]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [79]:
#ndim (no of dimension)
a1.ndim

1

In [80]:
a2.ndim

2

In [81]:
a3.ndim

3

In [82]:
# shape (rows,columns)
a1.shape

(10,)

In [83]:
a2.shape

(3, 4)

In [84]:
a3.shape

(2, 2, 2)

In [85]:
# size
a3.size

8

In [86]:
a2.size

12

In [87]:
# itemsize
a3.itemsize

4

In [88]:
a2.itemsize

8

In [90]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [92]:
# astype
a3.dtype

dtype('int32')

In [94]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operations

In [96]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [98]:
a1,a2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [99]:
# scalar operations

# arithmtic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [102]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [103]:
# vector operations
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [104]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [105]:
# Array Functions

In [106]:
a1 =np.random.random((3,3))
a1 =np.round(a1*100)

a1

array([[84., 75., 24.],
       [76., 93., 70.],
       [13.,  9., 29.]])

In [120]:
# max/min/sum/prod
# 0 -> col and 1 -> row

In [121]:
np.max(a1)

93.0

In [122]:
np.min(a1)

9.0

In [123]:
np.sum(a1)

473.0

In [124]:
np.prod(a1)

253822566816000.0

In [125]:
np.max(a1,axis=1)

array([84., 93., 29.])

In [126]:
a1

array([[84., 75., 24.],
       [76., 93., 70.],
       [13.,  9., 29.]])

In [127]:
np.min(a1,axis=1)

array([24., 70.,  9.])

In [128]:
# mean/median/std/var

In [130]:
np.mean(a1,axis=0)

array([57.66666667, 59.        , 41.        ])

In [131]:
# trigonomoetric functions

In [132]:
np.sin(a1)

array([[ 0.73319032, -0.38778164, -0.90557836],
       [ 0.56610764, -0.94828214,  0.77389068],
       [ 0.42016704,  0.41211849, -0.66363388]])

In [135]:
# dot product
a3=np.arange(12).reshape(3,4)
a4=np.arange(12,24).reshape(4,3)

In [136]:
np.dot(a3,a4)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [137]:
# log and exponents

In [140]:
np.exp(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [141]:
np.log(a1)

C:\Users\khadarbasha\AppData\Local\Temp\ipykernel_6988\2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [144]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[98., 76., 84.],
       [93., 38., 41.]])

In [145]:
np.floor(np.random.random((2,3))*100)

array([[75., 83., 73.],
       [67., 86., 87.]])

In [146]:
np.ceil(np.random.random((2,3))*100)

array([[13., 29., 63.],
       [98., 68., 82.]])

## Indexing and Slicing

In [147]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [148]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [149]:
a1[-1]

9

In [150]:
a1[0]

0

In [151]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a2[1]

array([4, 5, 6, 7])

In [153]:
a2[1][2]

6

In [154]:
a2[2][3]

11

In [155]:
a2[2,3]

11

In [156]:
a2[1,0]

4

In [157]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [158]:
a3[1,0,1]

5

In [159]:
a3[0,1,0]

2

In [160]:
a3[0,0,0]

0

In [161]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
a1[2:5]

array([2, 3, 4])

In [163]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
a2[0,:]

array([0, 1, 2, 3])

In [165]:
a2[:,2]

array([ 2,  6, 10])

In [167]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [168]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [174]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [176]:
a2[1,::3]

array([4, 7])

In [178]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [179]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
a3=np.arange(27).reshape(3,3,3)

In [181]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [183]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [184]:
a3[0,1,:]

array([3, 4, 5])

In [185]:
a3[1,:,1]

array([10, 13, 16])

In [188]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [192]:
a3[0::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [193]:
# Iterating

In [194]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [196]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [198]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [199]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [200]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [201]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [202]:
# reshape

In [207]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [210]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [219]:
# Horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [220]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [222]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [223]:
# Vertical stacking

In [224]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [225]:
# Spliting

In [226]:
# horizonal spliting

In [228]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [231]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [227]:
# vertical spliting

In [232]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [233]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]