In [1]:
import numpy as np

In [2]:
# Q1 Create a null vector of size 10 but the fifth value which is 1.


In [9]:
a=np.nan*np.empty(10)

In [11]:
a[4]=1

In [12]:
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

In [13]:
#Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) 
#and print the array and avg of the array.

In [14]:
a=int(input("Enter a value :"))
b=int(input("Enter b value :"))

x=np.random.random((a,b))

Enter a value :3
Enter b value :3


In [15]:
x

array([[0.27708059, 0.17394667, 0.21337835],
       [0.54843392, 0.55991004, 0.12097906],
       [0.17842719, 0.4825535 , 0.59502315]])

In [16]:
x.mean()

0.34997027443214984

In [17]:
#Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. 
#Take 2-D array shape as (a,b) as parameter to function.

# Eg.-
# [[1,1,1,1],
# [1,0,0,1],
# [1,0,0,1],
# [1,1,1,1]]

In [21]:
x=np.ones((4,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
x[1:-1,1:-1]=0

In [34]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
# Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [50]:
y=np.linspace(0,1,12,endpoint=True)[1:-1]

In [51]:
y

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [52]:
# Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
# Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [63]:
z=np.zeros((5,5))
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [68]:
# Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, 
# and coordinates of a point as array is given. Create an array of distance of each point in the random vectros 
# from the given point. Distance array should be interger type.

p=np.array([2,3])
a=np.random.randint(1,100,(10,2))
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)

array([ 26,  85, 121, 114, 128,  68, 102,  81,  83,  99])

In [69]:
# Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [71]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [72]:
# Q-9: Arrays
# You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

In [74]:
# Input Format:
# A single line of input containing space separated numbers.
# Output Format:
# Print the reverse NumPy array with type float.

# Example 1:
# Input:
# 1 2 3 4 -8 -10

a=input().strip().split()
np.array(a[::-1],dtype=np.float32)

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

In [75]:
#Q-10: Elements count
#Count the number of elements of a numpy array.

In [76]:
np.array([])

array([], dtype=float64)

In [78]:
print("elements_count  :",len(np.array([])))

elements_count  : 0


In [79]:
print("elements_count  :",len(np.array([1, 2])))

elements_count  : 2


In [80]:
a=np.array([])
a=np.array([1,2])
a=np.zeros((2,3))
a.size

6