In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [8]:
# Filling the numpy array with NaN values
a=np.nan*np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [16]:
a,b=map(int,input("Enter the a,b values :").split())
#print(a,b)
x=np.random.random((a,b))
print(x)
np.mean(x)

Enter the a,b values :2 5
[[0.16030705 0.10067165 0.97971424 0.40826517 0.77226038]
 [0.6786588  0.44959758 0.41595144 0.13595643 0.15658644]]


0.4257969189593188

### `Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [25]:
# a=np.ones((4,5))
# a[1:-1,1:-1]=0
# a

def borderArray(a,b):
    a=np.ones((a,b))
    a[1:-1,1:-1]=0
    return a

borderArray(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [29]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [35]:
z=np.zeros((5,5))
z
z+=np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```

<img src="https://d138zd1ktt9iqe.cloudfront.net/media/seo_landing_files/formula-of-euclidean-distance-1624039148.png"/>


In [48]:
a=np.random.randint(1,100,(10,2))
p=np.array([2,3])
print(a)
np.sqrt(np.sum((a-p)**2,axis=1)).astype(int)

[[56 99]
 [97 86]
 [88 27]
 [37 12]
 [53 26]
 [21 64]
 [48 18]
 [46 61]
 [66 33]
 [76 97]]


array([110, 126,  89,  36,  55,  63,  48,  72,  70, 119])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [51]:
# a=np.zeros((6,7,8))
# a
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [56]:
a=input().strip().split()
np.array(a[::-1],dtype=np.float32)

1 2 3 4 -8 -10


array([-10.,  -8.,   4.,   3.,   2.,   1.], dtype=float32)

### `Q-10:` Elements count

Count the number of elements of a numpy array.

**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [59]:
a=np.array([])
a.size
b=np.array([1, 2])
b.size
a=np.zeros((2,3))
a.size

6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [65]:
def softmax(arr):
    s=np.sum(np.exp(arr))
    return np.exp(arr)/s

#softmax(np.arange(5))
softmax(np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [76]:
def prepareVstack(*args):
    for i in args:
        if type(i)!=np.ndarray:
            raise TypeError("Required Numpy Array")
    return np.vstack(args)


a=np.arange(10).reshape(2,-1)
print("a=",a)
b=np.repeat(1,10).reshape(2,-1)
print("b=",b)

print(prepareVstack(a,b))

c=np.random.random((2,5))
print("c=",c)
print(prepareVstack(a,b,c))

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.14440048 0.84693059 0.60943259 0.88151254 0.61146827]
 [0.12818255 0.18672555 0.97784006 0.02897375 0.58056596]]
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.14440048 0.84693059 0.60943259 0.88151254 0.61146827]
 [0.12818255 0.18672555 0.97784006 0.02897375 0.58056596]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.


**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [84]:
def date_array(start,end):
    if type(start)!=str or type(end)!=str:
        raise TypeError
    
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}
    end=end.split('-')
    end_last=int(end[-1])+1
    
    if total_days_of_month[end[-2]] < end_last:
        days_diff=end_last-total_days_of_month[end[-2]]
        end[-1]=f'0{days_diff}' if days_diff<10 else f'{days_diff}'
        next_month=int(end[-2])+1
        end[-2]=f'0{next_month}' if next_month<10 else f'{next_month}'
    else:
        end[-1]=f'0{end_last}' if end_last<10 else f'{end_last}'
        
    #print(end[-2])
    end='-'.join(end)
     
    return np.arange(start,end,dtype='datetime64[D]')

date_array(start = '2020-11-15', end = '2020-11-30')

array(['2020-11-15', '2020-11-16', '2020-11-17', '2020-11-18',
       '2020-11-19', '2020-11-20', '2020-11-21', '2020-11-22',
       '2020-11-23', '2020-11-24', '2020-11-25', '2020-11-26',
       '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30'],
      dtype='datetime64[D]')

### `Q-14:` Subtract the mean of each row from a matrix.

In [85]:
x=np.random.random((5,4))
print(x)

[[0.18359477 0.65014327 0.1301019  0.26432095]
 [0.28086687 0.69845923 0.50659197 0.97928311]
 [0.13983358 0.24801579 0.07599787 0.82873946]
 [0.57318551 0.51896569 0.50583822 0.85016904]
 [0.70925749 0.37352039 0.48918814 0.60301747]]


In [90]:
print(x.mean(axis=1,keepdims=True))
x-x.mean(axis=1,keepdims=True)

[[0.30704022]
 [0.61630029]
 [0.32314667]
 [0.61203962]
 [0.54374587]]


array([[-0.12344546,  0.34310305, -0.17693832, -0.04271927],
       [-0.33543342,  0.08215893, -0.10970832,  0.36298281],
       [-0.1833131 , -0.07513089, -0.2471488 ,  0.50559279],
       [-0.03885411, -0.09307392, -0.10620139,  0.23812942],
       [ 0.16551162, -0.17022548, -0.05455773,  0.0592716 ]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [97]:
a=np.arange(9).reshape(3,3)
print(a)
a[:,[0,2,1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

### `Q-16:` Replace odd elements in arrays with -1.

In [101]:
a=np.arange(10)
a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [105]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

a[b>a]=b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)

In [106]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)

[[1930 8771  858 8591 6681]
 [5011 4394  919 3521 5737]
 [9059 8692  611 8747  536]
 [7090 3950 7749  776  714]
 [9099 7344 2639 6817 6838]
 [   9 9151 7907 2435 2507]
 [6525 1977 8456 6528 7898]
 [ 891 8168 9911 5680 7906]]


In [109]:
arr1[:,::2]

array([[1930,  858, 6681],
       [5011,  919, 5737],
       [9059,  611,  536],
       [7090, 7749,  714],
       [9099, 2639, 6838],
       [   9, 7907, 2507],
       [6525, 8456, 7898],
       [ 891, 9911, 7906]])

In [113]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.19400121, 0.88487174, 0.08574025, 0.8666936 , 0.67380327],
       [0.50515047, 0.44283983, 0.09190063, 0.35467582, 0.578469  ],
       [0.91395678, 0.87689356, 0.0607958 , 0.88244799, 0.05322157],
       [0.71510806, 0.3980004 , 0.78166027, 0.0774591 , 0.07119774],
       [0.91799636, 0.74075944, 0.26560291, 0.68753787, 0.68965865],
       [0.        , 0.92324783, 0.79761664, 0.24500101, 0.25227227],
       [0.65804888, 0.19874773, 0.85305999, 0.65835185, 0.79670774],
       [0.08907291, 0.82397495, 1.        , 0.57271258, 0.79751565]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [114]:
def nthmax(arr,n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]


nthmax(np.array([12,34,40,7,1,0]),2)

34

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [116]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [117]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [118]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [120]:
np.hstack([np.repeat(a,3),np.tile(a,3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])